package pydecompiler.dis;

import pydecompiler.dis.Pyc.Opcode;


public class python_10 {

  Opcode python_10_map(Opcode id)
{
    switch (id.ordinal()) {
    case 0:
      return Opcode.STOP_CODE;

    case 1:
      return Opcode.POP_TOP;
    case 2:
      return Opcode.ROT_TWO;
    case 3:
      return Opcode.ROT_THREE;
    case 4:
      return Opcode.DUP_TOP;
    case 10:
      return Opcode.UNARY_POSITIVE;
    case 11:
      return Opcode.UNARY_NEGATIVE;
    case 12:
      return Opcode.UNARY_NOT;
    case 13:
      return Opcode.UNARY_CONVERT;
    case 14:
      return Opcode.UNARY_CALL;
    case 15:
      return Opcode.UNARY_INVERT;
    case 20:
      return Opcode.BINARY_MULTIPLY;
    case 21:
      return Opcode.BINARY_DIVIDE;
    case 22:
      return Opcode.BINARY_MODULO;
    case 23:
      return Opcode.BINARY_ADD;
    case 24:
      return Opcode.BINARY_SUBTRACT;
    case 25:
      return Opcode.BINARY_SUBSCR;
    case 26:
      return Opcode.BINARY_CALL;
    case 30:
      return Opcode.SLICE_0;
    case 31:
      return Opcode.SLICE_1;
    case 32:
      return Opcode.SLICE_2;
    case 33:
      return Opcode.SLICE_3;
    case 40:
      return Opcode.STORE_SLICE_0;
    case 41:
      return Opcode.STORE_SLICE_1;
    case 42:
      return Opcode.STORE_SLICE_2;
    case 43:
      return Opcode.STORE_SLICE_3;
    case 50:
      return Opcode.DELETE_SLICE_0;
    case 51:
      return Opcode.DELETE_SLICE_1;
    case 52:
      return Opcode.DELETE_SLICE_2;
    case 53:
      return Opcode.DELETE_SLICE_3;
    case 60:
      return Opcode.STORE_SUBSCR;
    case 61:
      return Opcode.DELETE_SUBSCR;
    case 70:
      return Opcode.PRINT_EXPR;
    case 71:
      return Opcode.PRINT_ITEM;
    case 72:
      return Opcode.PRINT_NEWLINE;
    case 80:
      return Opcode.BREAK_LOOP;
    case 81:
      return Opcode.RAISE_EXCEPTION;
    case 82:
      return Opcode.LOAD_LOCALS;
    case 83:
      return Opcode.RETURN_VALUE;
    case 86:
      return Opcode.BUILD_FUNCTION;
    case 87:
      return Opcode.POP_BLOCK;
    case 88:
      return Opcode.END_FINALLY;
    case 89:
      return Opcode.BUILD_CLASS;
    case 90:
      return Opcode.STORE_NAME_A;
    case 91:
      return Opcode.DELETE_NAME_A;
    case 92:
      return Opcode.UNPACK_TUPLE_A;
    case 93:
      return Opcode.UNPACK_LIST_A;
    case 94:
      return Opcode.UNPACK_ARG_A;
    case 95:
      return Opcode.STORE_ATTR_A;
    case 96:
      return Opcode.DELETE_ATTR_A;
    case 97:
      return Opcode.STORE_GLOBAL_A;
    case 98:
      return Opcode.DELETE_GLOBAL_A;
    case 99:
      return Opcode.UNPACK_VARARG_A;
    case 100:
      return Opcode.LOAD_CONST_A;
    case 101:
      return Opcode.LOAD_NAME_A;
    case 102:
      return Opcode.BUILD_TUPLE_A;
    case 103:
      return Opcode.BUILD_LIST_A;
    case 104:
      return Opcode.BUILD_MAP_A;
    case 105:
      return Opcode.LOAD_ATTR_A;
    case 106:
      return Opcode.COMPARE_OP_A;
    case 107:
      return Opcode.IMPORT_NAME_A;
    case 108:
      return Opcode.IMPORT_FROM_A;
    case 110:
      return Opcode.JUMP_FORWARD_A;
    case 111:
      return Opcode.JUMP_IF_FALSE_A;
    case 112:
      return Opcode.JUMP_IF_TRUE_A;
    case 113:
      return Opcode.JUMP_ABSOLUTE_A;
    case 114:
      return Opcode.FOR_LOOP_A;
    case 115:
      return Opcode.LOAD_LOCAL_A;
    case 116:
      return Opcode.LOAD_GLOBAL_A;
    case 120:
      return Opcode.SETUP_LOOP_A;
    case 121:
      return Opcode.SETUP_EXCEPT_A;
    case 122:
      return Opcode.SETUP_FINALLY_A;
    case 123:
      return Opcode.RESERVE_FAST_A;
    case 124:
      return Opcode.LOAD_FAST_A;
    case 125:
      return Opcode.STORE_FAST_A;
    case 126:
      return Opcode.DELETE_FAST_A;
    case 127:
      return Opcode.SET_LINENO_A;
    default:
      return Opcode.PYC_INVALID_OPCODE;
    }
}

  int python_10_unmap(Opcode id)
{
    switch (id) {
    case BINARY_ADD:
      return 23;
    case BINARY_CALL:
      return 26;
    case BINARY_DIVIDE:
      return 21;
    case BINARY_MODULO:
      return 22;
    case BINARY_MULTIPLY:
      return 20;
    case BINARY_SUBSCR:
      return 25;
    case BINARY_SUBTRACT:
      return 24;
    case BREAK_LOOP:
      return 80;
    case BUILD_CLASS:
      return 89;
    case BUILD_FUNCTION:
      return 86;
    case BUILD_LIST_A:
      return 103;
    case BUILD_MAP_A:
      return 104;
    case BUILD_TUPLE_A:
      return 102;
    case COMPARE_OP_A:
      return 106;
    case DELETE_ATTR_A:
      return 96;
    case DELETE_FAST_A:
      return 126;
    case DELETE_GLOBAL_A:
      return 98;
    case DELETE_NAME_A:
      return 91;
    case DELETE_SLICE_0:
      return 50;
    case DELETE_SLICE_1:
      return 51;
    case DELETE_SLICE_2:
      return 52;
    case DELETE_SLICE_3:
      return 53;
    case DELETE_SUBSCR:
      return 61;
    case DUP_TOP:
      return 4;
    case END_FINALLY:
      return 88;
    case FOR_LOOP_A:
      return 114;
    case IMPORT_FROM_A:
      return 108;
    case IMPORT_NAME_A:
      return 107;
    case JUMP_ABSOLUTE_A:
      return 113;
    case JUMP_FORWARD_A:
      return 110;
    case JUMP_IF_FALSE_A:
      return 111;
    case JUMP_IF_TRUE_A:
      return 112;
    case LOAD_ATTR_A:
      return 105;
    case LOAD_CONST_A:
      return 100;
    case LOAD_FAST_A:
      return 124;
    case LOAD_GLOBAL_A:
      return 116;
    case LOAD_LOCALS:
      return 82;
    case LOAD_LOCAL_A:
      return 115;
    case LOAD_NAME_A:
      return 101;
    case POP_BLOCK:
      return 87;
    case POP_TOP:
      return 1;
    case PRINT_EXPR:
      return 70;
    case PRINT_ITEM:
      return 71;
    case PRINT_NEWLINE:
      return 72;
    case RAISE_EXCEPTION:
      return 81;
    case RESERVE_FAST_A:
      return 123;
    case RETURN_VALUE:
      return 83;
    case ROT_THREE:
      return 3;
    case ROT_TWO:
      return 2;
    case SETUP_EXCEPT_A:
      return 121;
    case SETUP_FINALLY_A:
      return 122;
    case SETUP_LOOP_A:
      return 120;
    case SET_LINENO_A:
      return 127;
    case SLICE_0:
      return 30;
    case SLICE_1:
      return 31;
    case SLICE_2:
      return 32;
    case SLICE_3:
      return 33;
    case STOP_CODE:
      return 0;
    case STORE_ATTR_A:
      return 95;
    case STORE_FAST_A:
      return 125;
    case STORE_GLOBAL_A:
      return 97;
    case STORE_NAME_A:
      return 90;
    case STORE_SLICE_0:
      return 40;
    case STORE_SLICE_1:
      return 41;
    case STORE_SLICE_2:
      return 42;
    case STORE_SLICE_3:
      return 43;
    case STORE_SUBSCR:
      return 60;
    case UNARY_CALL:
      return 14;
    case UNARY_CONVERT:
      return 13;
    case UNARY_INVERT:
      return 15;
    case UNARY_NEGATIVE:
      return 11;
    case UNARY_NOT:
      return 12;
    case UNARY_POSITIVE:
      return 10;
    case UNPACK_ARG_A:
      return 94;
    case UNPACK_LIST_A:
      return 93;
    case UNPACK_TUPLE_A:
      return 92;
    case UNPACK_VARARG_A:
      return 99;
    default: return -1;
    }
}

}
